# Generated by Django 4.2.2 on 2023-07-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_teacher_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
