# Generated by Django 4.2.2 on 2023-07-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachingsession',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='teachingsession',
            name='expertise',
            field=models.CharField(choices=[('phy', 'Physics'), ('chem', 'Chemistry'), ('math', 'Mathematics'), ('comp', 'Computer Science'), ('humn', 'Humanities'), ('bio', 'Biology'), ('zoo', 'Zoology'), ('bot', 'Botany')], max_length=255),
        ),
    ]
