# Generated by Django 4.2.2 on 2023-07-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_sessions', '0002_remove_teachingsession_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('interrupted', 'Interrupted'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('meeting_id', models.CharField(max_length=255)),
                ('duration', models.FloatField()),
                ('join_url', models.URLField()),
                ('teaching_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_sessions.teachingsession')),
            ],
        ),
    ]
